[services]
lutris = False
gog = False
egs = False
origin = False
ubisoft = False
steam = True

[lutris]
dismiss-missing-vulkan-library-warning = True
width = 1822
height = 936
window_x = 45
window_y = 45
maximized = False
selected_category = category:all
hide_client_on_game_start = True
library_ignores = 
migration_version = 12

